version: 2.0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  Version: $(APPVEYOR_BUILD_VERSION)
  GithubRepo: $(APPVEYOR_REPO_NAME)
build_script:
- build.cmd Release
test:
  assemblies:
    - '**\Carnac.Tests.dll'
artifacts:
- path: deploy\*.nupkg
  name: ChocoPackage
- path: deploy\*.zip
  name: ZipPackage
deploy:
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: sMCceYyOHQxaJMpcWBGmbGkbB6aYToUWm3rqfLv1ZZaeToqM2PAz1or18hnJbon0
  skip_symbols: true
  artifact: ChocoPackage
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: ImWN38cmVAwBXYkDM1L6kxkkOlrB05vD5vGMQh8bFc/GecEiwvtsemQXYmCozxBe
  artifact: ZipPackage
  draft: false
  on:
    branch: master
